services:
  app:
    image: 'simple-banking:latest'
    build:
      context: .
    container_name: app
    ports:
      - '8081:8081'
    depends_on:
      - db
      - rabbit
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/banking?characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=hendi34
      - SPRING_RABBITMQ_HOST=rabbit

  db:
    image: 'postgres:16-alpine3.19'
    container_name: db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hendi34
      - POSTGRES_DB=banking
    volumes:
      - ./src/main/resources/ddl/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql

  rabbit:
    image: 'rabbitmq:management-alpine'
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
