-- CREATE DATABASE banking_db ENCODING = 'UTF8' LC_COLLATE = 'et_EE.utf8' LC_CTYPE = 'et_EE.utf8';

CREATE TABLE public.accounts
(
    id          int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id varchar      NOT NULL,
    country     varchar(255) NOT NULL,
    CONSTRAINT accounts_pkey PRIMARY KEY (id)
);

CREATE TABLE public.balances
(
    id         int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    amount     numeric      NOT NULL DEFAULT 0,
    currency   varchar(255) NOT NULL,
    account_id int8         NOT NULL,
    CONSTRAINT balance_positive CHECK ((amount >= (0)::NUMERIC)),
    CONSTRAINT balances_account_id_currency_key UNIQUE (account_id, currency),
    CONSTRAINT balances_pkey PRIMARY KEY (id),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.accounts (id) ON DELETE CASCADE
);

CREATE TABLE public.transactions
(
    id          int8          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id  int8          NOT NULL,
    currency    varchar(255)  NOT NULL,
    amount      numeric       NOT NULL DEFAULT 0,
    direction   varchar(2255) NOT NULL,
    description varchar(255)  NOT NULL,
    CONSTRAINT amount_positive CHECK ((amount >= (0)::NUMERIC)),
    CONSTRAINT transactions_pkey PRIMARY KEY (id),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.accounts (id) ON DELETE CASCADE
);
